---
- hosts: ""
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install Docker Module for Python docker-py
      pip:
        name: docker-py
        state: present
    - name: Create a data container
      community.docker.docker_container:
        name: mydata
        image: busybox
        volumes:
          - /data

    - name: Re-create a redis container
      community.docker.docker_container:
        name: myredis
        image: redis
        command: redis-server --appendonly yes
        state: present
        recreate: true
        published_ports:
          - 0.0.0.0:8080:8080
        volumes_from:
          - mydata
