---
- hosts: dev
  user: ansible
  become: True
  connection: ssh
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: System Reload
      ansible.builtin.systemd:
        daemon-reload: yes
   handlers:
    - name: restart docker
      service:
      name: docker
      state: restarted
    - name: Docker Run
      service:
        name: docker.service
        state: started
        enabled: yes
