- hosts: dev
  become: True
  tasks:
   - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
        
   - name: Starting docker and enable
     service:
        name: "docker"
        state: started
        enabled: yes
   - name: Install docker-py python module
     pip:
       name: docker-py
       state: present

   - name: Installation of required packages by docker
     command: "pip3 install docker"

   - name: Start the container
     docker_container:
       name: appsecco
       image: "swanandd55/appsecco:{{DOCKER_TAG}}"
       state: started
       published_ports:
         - 0.0.0.0:8080:8080
