---
- hosts: ""
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container service
      docker_container:
        name: appsecco
        image: "swanandd55/appsecco:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - "0.0.0.0::"
