---
- hosts: dev
  user: ansible
  become: True
  connection: ssh
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: System Reload
      ansible.builtin.systemd:
        daemon-reload: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
  tasks:
    - name: Docker Run
      service:
        name: docker
        state: started
        enabled: yes
    - name: Start the container
      docker_container:
        name: appsecco
        image: "swanandd55/appsecco:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
