---
- hosts: ""
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install Docker Module for Python docker-py
      pip:
        name: docker-py
        state: present
    - name: Create a data container
      community.docker.docker_container:
        name: mydata
        image: busybox
        volumes:
          - /data
    - name: Re-create a redis container
      community.docker.docker_container:
        name: myredis
        image: redis
        command: redis-server --appendonly yes
        state: present
        recreate: true
        exposed_ports:
          - 6379
        volumes_from:
          - mydata
    - name: Restart a container
      community.docker.docker_container:
        name: appsecco
        image: swanandd55/appsecco:{{DOCKER_TAG}}
        state: started
        restart: true
        ports:
          - "8080:9000"
