- hosts: dev
  tasks:

   - name: Creation of yum repo
     yum_repository:
         name: asifrepo
         baseurl: https://download.docker.com/linux/rhel/docker-ce.repo
         description : My repo
         gpgcheck: 0

   - name: Installation of docker in managed node
     package:
        name: "docker-ce"
        state: present

   - name: Starting docker and enable
     service:
        name: "docker"
        state: started
        enabled: yes

   - name: Installation of required packages by docker
     command: "pip3 install docker"

   - name: Start the container
     docker_container:
       name: appsecco
       image: "swanandd55/appsecco:{{DOCKER_TAG}}"
       state: started
       published_ports:
         - 0.0.0.0:8080:8080
